create table TEACHERS(
    TEACHER_ID INT AUTO_INCREMENT PRIMARY KEY,
    EMAIL VARCHAR(255),
    PASS VARCHAR(255)
);

CREATE TABLE QUIZZES(
    QUIZ_ID INT AUTO_INCREMENT PRIMARY KEY,
    TEACHER_ID INT,
    TITLE VARCHAR(255),
    COMPLETIONSTATE ENUM('LIVE','INACTIVE','COMPLETED','DRAFT') ,
    FOREIGN KEY (TEACHER_ID) REFERENCES TEACHERS(TEACHER_ID)
);

CREATE TABLE QUESTIONS(
    QUESTION_ID INT AUTO_INCREMENT PRIMARY KEY,
    QUIZ_ID INT,
    QUESTION VARCHAR(255),
    CHOICES JSON,
    CORRECT_ANSWER INT,
    QUESTION_ORDER INT,
    FOREIGN KEY (QUIZ_ID) REFERENCES QUIZZES(QUIZ_ID)
);

CREATE TABLE STUDENTS(
    STUDENT_ID INT AUTO_INCREMENT PRIMARY KEY,
    STUDENT_NAME VARCHAR(255),
    POINTS INT,
    STREAK INT,
    QUIZ_ID INT,
    FOREIGN KEY (QUIZ_ID) REFERENCES QUIZZES(QUIZ_ID)
);

CREATE TABLE COMMENTS(
    COMMENTS_ID INT AUTO_INCREMENT PRIMARY KEY,
    STUDENT_ID INT,
    QUIZ_ID INT,
    COMMENT_TEXT VARCHAR(255),
    FOREIGN KEY (STUDENT_ID) REFERENCES STUDENTS(STUDENT_ID),
    FOREIGN KEY (QUIZ_ID) REFERENCES QUIZZES(QUIZ_ID)
);